version: "3"

services:
  web:
    container_name: "backend_incora"
    build: ./web
    volumes:
      - .:/Test_Incora
    ports:
      - "8011:8010"
    depends_on:
      - db
    networks:
      - web
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  db:
    container_name: "postgresql_incora"
    image: postgres:14-alpine3.15
    restart: always
    volumes:
      - ./postgres_db:/var/lib/postgresql
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5454:5432"
    networks:
      - web

  redis_container:
    container_name: redis_incora
    image: redis:7.0-rc1-bullseye
    ports:
      - "6364:6379"
    networks:
      - web

networks:
  web:
    driver: bridge